### ISSUE TITLE
[BUG] Quatree performance when scene have static objects

### ISSUE THREAD

**Issue by Dartemiss** [Unnamed-Company/LittleOrionEngine#10]
**Describe the bug**
When using quadtree culling or combined culling. If the quadtree has divisions (grater number of static objects than quadtree bucket size) then the performance of the 'mouse picking' starts going very slow and can take 1/2 seconds to select an object. I assume this is because the function `GetRaycastIntertectedObject()` is calling `GetCullingMeshes(App->cameras->scene_camera)` that uses the quadtree to get the meshes that have to be rendered.

**To Reproduce**
1. Set some objects static (5 or 6)
2. Click on an object to use mouse picking
3. See error

**Expected behavior**
Mouse picking should be immediate.

**Screenshots**
`https://gyazo.com/b9253d586c7d8e1b6d6f0de9ee69411b`

**Comment by mariofv** [comment]
This bug is gonna be revised in #15

**Comment by mariofv** [comment]
Solved in #85
