### ISSUE TITLE
[BUG] Prefabs with animation loads a empty component animation when loading scene / stoping game loop

### ISSUE THREAD

**Issue by Dartemiss** [Unnamed-Company/LittleOrionEngine#102]
**Describe the bug**
Unwanted empty components animation are created on prefabs when loading.

**To Reproduce**
1. Drag Idle.fbx on scene, put stm on animation.
2. Save.
3. Press play twice or load scene again.

**Expected behavior**
Prefabs only should add component animation by default if created from project explorer.

**Screenshots**

**Additional context**

**Comment by yalania** [comment]
As I was unable to reproduce it I'm going to close it and if it happens again you can reopen it.
