### ISSUE TITLE
[BUG] Saving new scene crashes the engine

### ISSUE THREAD

**Issue by raulgonzalezupc** [Unnamed-Company/LittleOrionEngine#107]
**Describe the bug**

When you try to save a new scene it crashes the engine. 

**To Reproduce**
1. Go to 'File'
2. Click on 'Save scene as'
3. See error

**Expected behavior**

Saving the scene and have it on the folder

**Screenshots**

![image](https://user-images.githubusercontent.com/56253770/81502918-343e0c80-92e1-11ea-9e37-2b83cc531fff.png)

**Additional context**

**Comment by Dartemiss** [comment]
Bug fixed on #109
