### ISSUE TITLE
[BUG] Error click folder in Project Explorer

### ISSUE THREAD

**Issue by JorxSS** [Unnamed-Company/LittleOrionEngine#111]
**Describe the bug**
When you try to click some foler if you don't have all the previous folders collapsed, you will open some folder form the previous main folder.

**To Reproduce**
1. Go to Project Explorer
2. Click on a main folder that have the previous main folder collapsed
3. See error

**Expected behavior**
Expand the selected folder.

**Screenshots**
![giphy](https://user-images.githubusercontent.com/49075678/81509314-f9040380-9309-11ea-9108-5e138a25877f.gif)

**Comment by yalania** [comment]
I did a quick fix but now the folder will only open when double clicked
