### ISSUE TITLE
[BUG] Scaling a GO 

### ISSUE THREAD

**Issue by JorxSS** [Unnamed-Company/LittleOrionEngine#12]
**Describe the bug**
When you apply any rotation to a GO and then you use the scale tool, the rotation will be restored.

**To Reproduce**
1. Select a GO
2. Apply some rotation.
3. Then scale the GO.

**Expected behavior**
The rotation of the object must remain the same.

**Screenshots**
![scaleerror](https://user-images.githubusercontent.com/49075678/74660948-5cf9ae80-5197-11ea-93b2-44378924a149.gif)

**Additional context**
Also can happen in some objects (Dollhouse) without applying a rotation.

**Comment by mariofv** [comment]
The bug happened because Gizmos where applying transformations in World space instead of local space. Solved in #13
