### ISSUE TITLE
[BUG] Texture colors are not saved.

### ISSUE THREAD

**Issue by JorxSS** [Unnamed-Company/LittleOrionEngine#120]
**Describe the bug**
Texture's main colors are not saved. Then if I put in Diffuse (example) a color there instead of a texture. When I save the scene the color is not stored then when I load the color is again white. Same happen when Play and Stop.

**To Reproduce**
1. Go to a model without texture.
2. Click on Color.
3. Select one different from black
4. Play or Save scene and then Stop or Load scene.
5. See error

**Expected behavior**
Colors being saved.

**Comment by mariofv** [comment]
Solved in commit [22f1b2f](https://github.com/OnionGalaxy/LittleOrionEngine/commit/22f1b2f9967e1fa7c85c9e6381f58bbaef179fa1)
