### ISSUE TITLE
[BUG] Emissive textures doesn't save

### ISSUE THREAD

**Issue by JorxSS** [Unnamed-Company/LittleOrionEngine#127]
**Describe the bug**
GO with emissive they are not being loaded after save.

**To Reproduce**
1. Go to a GO with textures
2. Put him an Emissive Texture
3. Save and Load

**Expected behavior**
Emissive texture being loaded properly.

**Comment by tonifj** [comment]
I'll assign this bug to @raulgolzalezupc

**Comment by mariofv** [comment]
Is this still happening @JorxSS ?

**Comment by JorxSS** [comment]
Not anymore we can close it
