### ISSUE TITLE
[BUG] Material type and Transparency are not saved.

### ISSUE THREAD

**Issue by JorxSS** [Unnamed-Company/LittleOrionEngine#128]
**Describe the bug**
Applying transparency to a texture, doesn't save his value. Also the material type is not saved either.

**To Reproduce**
1. Go to a GO with textures.
2. Click on material type set it to transparent.
3. Put it transparency to some value.
4. Save and Load.
5. See error

**Expected behavior**
Transparency and material type being loaded properly.

**Comment by mariofv** [comment]
Solved in commit [22f1b2f](https://github.com/OnionGalaxy/LittleOrionEngine/commit/22f1b2f9967e1fa7c85c9e6381f58bbaef179fa1)
