### ISSUE TITLE
[BUG] Loading GO with Normal or Occlusion texture, crash the engine.

### ISSUE THREAD

**Issue by JorxSS** [Unnamed-Company/LittleOrionEngine#129]
**Describe the bug**
Loading GO with Normal or Occlusion texture crash the engine.

**To Reproduce**
1. Go to a GO with material assigned.
2. Assign a normal or occlusion texture.
3. Save and Load.

**Expected behavior**
Engine able to load a normal texture.

**Comment by tonifj** [comment]
Unable to reproduce

**Comment by JorxSS** [comment]
I already showed the error to @yalania, this bug doesn't appear always, appears randomly

**Comment by yalania** [comment]
This was because a memory leak in prefabs, as the allocated components where not deleted. Already fixes in the feature/character_gameplay branch
