### ISSUE TITLE
[BUG] Shaders of the material are not saved on scene

### ISSUE THREAD

**Issue by Dartemiss** [Unnamed-Company/LittleOrionEngine#130]
**Describe the bug**
When working on a scene if you change the shader that change is not saved on the scene as if you delete library the default shader is chosen by default.

**To Reproduce**
1. Change shader of an object to Skinning.
2. Save scene
3. Delete library

**Expected behavior**

**Comment by mariofv** [comment]
This is expected at the moment, we need to change how Fbx are imported
