### ISSUE TITLE
[BUG] If I move a child from a Prefab, their new transform is not saved and if I click apply after moving it, crashes the Engine

### ISSUE THREAD

**Issue by JorxSS** [Unnamed-Company/LittleOrionEngine#131]
**Describe the bug**
Prefab's child transform are not saved after save, and if I click apply the engine crashes.

**To Reproduce**
1. Go to child GO from a Prefab
2. Move it
3. Click Apply (see crash) or Save and Load the scene

**Expected behavior**
New child transform saved and click apply doesn't crash the engine.

**Screenshots**
![image](https://user-images.githubusercontent.com/49075678/82210978-5bfc2880-9910-11ea-826f-3a655fde1f1b.png)

**Comment by yalania** [comment]
when you say Move it you mean change the transform or change the hierarchy?

**Comment by JorxSS** [comment]
move the transform

**Comment by yalania** [comment]
The actual bug is that this button appears for fbx when it shouldn't

**Comment by yalania** [comment]
Added a new parameter in json for checking when a file is overwritable or not so we don't have the apply button wrongly.
