### ISSUE TITLE
[BUG] Prefabs active status is not stored

### ISSUE THREAD

**Issue by mariofv** [Unnamed-Company/LittleOrionEngine#140]
**Describe the bug**
If you instantiate a prefab and disable one  of its child gameobjects. this change is not stored when Saving/Loading the scene.

**To Reproduce**
1. Instantiate the model `Cube.fbx`
2. Disable it's child.
3. Save the scene, then load it.
4. See how the child is enabled again.

**Expected behavior**
Enable changes are persistent

**Comment by yalania** [comment]
fix https://github.com/OnionGalaxy/LittleOrionEngine/pull/143
