### ISSUE TITLE
[FEATURE] ModuleSpacePartitioning

### ISSUE THREAD

**Issue by mariofv** [Unnamed-Company/LittleOrionEngine#15]
**Is your feature request related to a problem? Please describe.**
At the moment space partitioning is managed by `ModuleRender`, and this makes thus class have to many responsabilities.

**Describe the solution you'd like**
Encapsulating all SpacePartitioning code in a new module, `ModuleSpacePartitioning`.

**Comment by Dartemiss** [comment]
Feature is now being implemented on https://github.com/OnionGalaxy/LittleOrionEngine/tree/feature/refactor_spacepartitioning

**Comment by mariofv** [comment]
Done in #85
