### ISSUE TITLE
[FEATURE] Move inside the State Machine window using middle mouse button

### ISSUE THREAD

**Issue by JoanStinson** [Unnamed-Company/LittleOrionEngine#155]
**Is your feature request related to a problem? Please describe.**
Currently, whenever I want to move inside the animator editor, aka the State Machine window, I move using the right click of the mouse, but this is very annoying as a pop-up of "Create State" appears all the time.

**Describe the solution you'd like**
Instead of moving around with the right click of the mouse, make it like in Unity with the middle button click of the mouse. It will make my life happier 😃 

**Additional context**
Problem I encounter all the time: https://gyazo.com/cb3ff85c13ee86289fcef9387abb4467

**Comment by mariofv** [comment]
@yalania Is this fixed in #166?

**Comment by yalania** [comment]
You can not move with the middle button, but now the "Create State" popup only appears when left clicking in the state machine background
