### ISSUE TITLE
[FEATURE] All Project Explorer folders collapsed by default

### ISSUE THREAD

**Issue by JoanStinson** [Unnamed-Company/LittleOrionEngine#156]
**Is your feature request related to a problem? Please describe.**
Every time I run the engine again, all the project explorer folders are opened and it's a bit tedious as I need to scroll a lot to find what I'm looking for. Also need to close them all manually and it's time consuming. It's also due to '.git' folders.

**Describe the solution you'd like**
By default, I think it's an ImGui Node Flag, have all the folders collapsed so it's easier to navigate 😄

**Additional context**
Like this: https://gyazo.com/50fb8ac3c853561803af2ee9d6293d6f

**Comment by JorxSS** [comment]
Done in #200
