### ISSUE TITLE
[FEATURE] All Hierarchy gameobjects collapsed when loading scene

### ISSUE THREAD

**Issue by JoanStinson** [Unnamed-Company/LittleOrionEngine#157]
**Is your feature request related to a problem? Please describe.**
Every time I run the engine again, all the gameobjects in the hierarchy are opened and it's a bit tedious as I need to scroll a lot to find what I'm looking for. Also need to close them all manually and it's time consuming. We are at a point were having a lot of gameobjects makes this be pretty annoying.

**Describe the solution you'd like**
By default, I think it's an ImGui Node Flag, when loading a scene have all the gameobjects in the Hierarchy collapsed so it's easier to navigate 😄

**Additional context**
It gets very annoying: https://gyazo.com/783908673e2817a3b2514a8947f9051d

**Comment by JorxSS** [comment]
Done in #200
