### ISSUE TITLE
[BUG] Engine crash when dropping fbx in hierarchy

### ISSUE THREAD

**Issue by yalania** [Unnamed-Company/LittleOrionEngine#17]
**Describe the bug**

The engine crashes when a fbx is dragged and dropped in the hierarchy in a new scene.
**To Reproduce**
1. Create a new scene
2. Drag and drop any fbx in the hierarchy

**Expected behavior**
The engine doesn't crash.

**Comment by Dartemiss** [comment]
Bug fixed in https://github.com/Unnamed-Company/LittleOrionEngine/pull/18.
