### ISSUE TITLE
[BUG] Duplicate GO does not store well the rotation

### ISSUE THREAD

**Issue by raulgonzalezupc** [Unnamed-Company/LittleOrionEngine#185]
**Describe the bug**
When duplicating a GO it does not duplicate it with the same values

**To Reproduce**
1. Go to some GO with rotation different than (0,0,0)
2. Click on Duplicate

**Screenshots**
https://gyazo.com/c6e40221592bb44d9a67f8119e4709cd

**Comment by yalania** [comment]
Fix for this https://github.com/OnionGalaxy/LittleOrionEngine/pull/247
