### ISSUE TITLE
[BUG] Critical memory leak when particles are active

### ISSUE THREAD

**Issue by Dartemiss** [Unnamed-Company/LittleOrionEngine#194]
**Describe the bug**
The memory of the process of the engine increases constantly.

**To Reproduce**
1. Open windows Task Manager and check LittleOrionEngine memory.
2. Open Level1.scene
3. Check that the memory of the process on the task manager will start to increase.
4. If you delete the GO Particles the memory stops to allocate

**Expected behavior**
No RAM BOOM

**Screenshots**
https://gyazo.com/f97b15d8efc8b2183c643ded1595d42c

https://gyazo.com/c7f880d7185ba06eda833d746f89c866

**Additional context**

**Comment by yalania** [comment]
fix https://github.com/OnionGalaxy/LittleOrionEngine/pull/196

**Comment by Dartemiss** [comment]
Solved in #196
