### ISSUE TITLE
[BUG] Engine crash when clicking while loading assets

### ISSUE THREAD

**Issue by yalania** [Unnamed-Company/LittleOrionEngine#24]
**Describe the bug**
Engine crash if the user clicks while loading.

**To Reproduce**
1. Remove all *.meta to force a new import
2. Open Engine
3.  Click on the screen while the loading bar is showing.

**Expected behavior**
Not crashing.

**Comment by mariofv** [comment]
Popup is not blocking Input by our side, so we must control this. I will work on this on my branch, I will link the PR when done!

**Comment by mariofv** [comment]
This is gonna be solved in #27

**Comment by mariofv** [comment]
Also is the same problem as #30, so I'm closing it
