### ISSUE TITLE
[BUG] When deleting a ComponentBillboard engine crashes if you have copied that component before

### ISSUE THREAD

**Issue by Dartemiss** [Unnamed-Company/LittleOrionEngine#246]
**Describe the bug**
Copy a component billboard then paste it. Deleting the original component will make the engine crash.

**To Reproduce**
1. Copy any ComponentBillboard
2. Paste it anywhere
3. Go to the original Component and delete it.

**Expected behavior**
No crashes 🗡️ 

**Screenshots**

**Additional context**

**Comment by yalania** [comment]
I will fix this when fixing prefabs, as the problem is in the clone fuction

**Comment by yalania** [comment]
Fix for this https://github.com/OnionGalaxy/LittleOrionEngine/pull/247
