### ISSUE TITLE
[BUG] Missing mesh when using prefabs and multithreading 

### ISSUE THREAD

**Issue by mariofv** [Unnamed-Company/LittleOrionEngine#249]
**Describe the bug**
Sometimes when loading meshes in `ComponentMeshRenderer` some meshes are not loaded at all (nullptr).

**To Reproduce**
1. Create a Prefab with a `ComponentMeshRenderer`.
2. Instantiate it and save the scene,
3. Load the scene again.
4. See error (None is displayed in `ComponentMeshRenderer` inspector.

**Expected behavior**
Mesh is loaded

**Additional context**
This bug is non-deterministic. The thing is that when loading the same object without prefabs it loads perfectly

**Comment by yalania** [comment]
We faced this problem before, probably missing the reasigne call somewhere.

**Comment by mariofv** [comment]
Fixed in #268
