### ISSUE TITLE
[BUG] When clicking in a configuration window you can click through it

### ISSUE THREAD

**Issue by yalania** [Unnamed-Company/LittleOrionEngine#30]
**Describe the bug**
When you have any other window in front of the scene window and you click on it, you will be clicking through it to the scene window.

**To Reproduce**
1. Open the engine with a loaded scene.
2. Open the configuration window and place in front of the scene.
3. Click on it an you will see object selected in the hierarchy.

**Expected behavior**
You can't  click things in the scene through the window.

**Screenshots**
![imatge](https://user-images.githubusercontent.com/48101863/76239962-bb63fb00-6232-11ea-87f3-9f946c86dc93.png)

**Comment by mariofv** [comment]
This is gonna be solved in #27

**Comment by mariofv** [comment]
Solved in #36
