### ISSUE TITLE
[BUG] When deleting GameOjects, clicking our scene window crashes the Engine

### ISSUE THREAD

**Issue by Pacasasgar** [Unnamed-Company/LittleOrionEngine#34]
It happens almost every time. GameObjects deleted for this test were created in the 'Debug' window 'Create houses scene' option. If you delete all auto-generated GameObjects in the hierarchy, then you will crash the engine by clicking the scene or trying to generate more houses.

Screenshot:
![image](https://user-images.githubusercontent.com/15977683/76652461-ed44cc80-6566-11ea-90f4-18d7d38e6998.png)

**Comment by Pacasasgar** [comment]
Steps to re-create the bug and crash the Engine:

1. As compilation succeds, go to 'File->New scene' to clear out the scene.
2. Enable 'Debug' window if you don't have it by going to 'Window->Debug'.
3. Select 'Create houses scene'.
4. Delete all GameObjects by right-clicking 'GameObject (31) -> Delete GameObject' in the Hierarchy.
5. Try to 'Create houses scene' again, it will crash.

Actually in step 5, more actions creates the 'crash' but it seems always the same reason.

**Comment by mariofv** [comment]
Because this bug is related to SpacePartitioning, it will be fixed in #15.
