### ISSUE TITLE
[BUG] Deleting folders in Project breaks engine

### ISSUE THREAD

**Issue by JordiRomagosa** [Unnamed-Company/LittleOrionEngine#42]
**Describe the bug**
Deleting folders in Project, sometimes it does nothing, and sometimes it breaks the engine.

**To Reproduce**
1. Select a folder inside Models folder.
2. Try Delete the folder.
3. Nothing happens.
4. Try Delete again without reselecting the folder.
5. Engine crashes.

**Expected behavior**
When deleting, the folder should be removed or asked a for confirmation, or at least a "you can't do it" message should pop up.
And it shouldn't crash when trying again.

**Screenshots**
The error that gives:
![imagen](https://user-images.githubusercontent.com/9912719/76781762-7ea67f80-67af-11ea-9d7b-057119977e52.png)

**Comment by mariofv** [comment]
Fixed in branch [feature/resource_management_improvements](https://github.com/OnionGalaxy/LittleOrionEngine/tree/feature/resource_management_improvements)
