### ISSUE TITLE
[BUG] Saving a Prefab crashes the engine

### ISSUE THREAD

**Issue by mariofv** [Unnamed-Company/LittleOrionEngine#45]
**Describe the bug**
When a scene containg prefabs is saved, the engine crashes.

**To Reproduce**
1. Create a new empty scene.
2. Add a new prefab GameObject from `FileExplorer`.
3. Save the scene.

**Expected behavior**
Not crashing.

**Comment by Dartemiss** [comment]
Issue fixed on https://github.com/OnionGalaxy/LittleOrionEngine/pull/47
