### ISSUE TITLE
[BUG] Importing for the first time crashes the engine

### ISSUE THREAD

**Issue by mariofv** [Unnamed-Company/LittleOrionEngine#46]
**Describe the bug**
Starting the engine in a clean repo or with diferent `.meta` files from the current repo makes the engine go boom.

**To Reproduce**
1. Clean the repo using `git clean -dfx`.
2. Start the engine.
3. Profit.

**Expected behavior**
Not crahsing

**Comment by yalania** [comment]
This is already fixed, I'm going to close it.
