### ISSUE TITLE
[BUG] Loading a scene that contains prefabs crashes the engine 

### ISSUE THREAD

**Issue by mariofv** [Unnamed-Company/LittleOrionEngine#58]
**Describe the bug**
When a scene that contains a prefab is loaded the engine crashes.

**To Reproduce**
1. Clone the repo again (this way we ensure that everything is clean).
2. Switch to branch `feature/vs1_build`. 
3. Once the engine is executed, load scene `Assets/Scenes/Main.scene`

**Expected behavior**
Not crashing.

**Comment by yalania** [comment]
fix: https://github.com/OnionGalaxy/LittleOrionEngine/pull/59
