### ISSUE TITLE
[BUG] Prefabs don't preserve hierarchy status when loading scene

### ISSUE THREAD

**Issue by Dartemiss** [Unnamed-Company/LittleOrionEngine#62]
**Describe the bug**
When you put more than one prefab as a child of an object and you save the scene and then load it. The prefabs will be loaded outside of their correct hierarchy. Being a child of root.

**To Reproduce**
1. Create a scene whith a empty object that have as childs more than one prefab.
2. Save Scene
3. Load Scene
4. See chaos :(

**Expected behavior**
Correct behaviour.

**Screenshots**
https://gyazo.com/5c84431db936cf69d4ee9134ab9b67be

**Additional context**

**Comment by yalania** [comment]
fix https://github.com/OnionGalaxy/LittleOrionEngine/pull/63/files
