### ISSUE TITLE
[BUG] Problem with Resource Cache

### ISSUE THREAD

**Issue by JorxSS** [Unnamed-Company/LittleOrionEngine#66]
**Describe the bug**
The resource cache it's not clear correctly and have unexpected behaviour after clear.

**To Reproduce**
1. Go to Menu scene
2. Click on Play
3. Click Spacebar to start "playing"
4. See error with models.

**Expected behavior**
All the models with their respective "textures".

**Screenshots**
Just see the black screen.

**Comment by JorxSS** [comment]
The actual solution is this: 
It's not a perfect solution but it works.

```
void ModuleResourceManager::CleanResourceCache()
{
    //auto it = std::remove_if(resource_cache.begin(), resource_cache.end(), [](const std::shared_ptr<Resource> & resource) {
    //    return resource.use_count() == 1;
    //});
    //resource_cache.erase(it, resource_cache.end());
    resource_cache.clear();
}
```

**Comment by yalania** [comment]
//auto it = std::remove_if(resource_cache.begin(), resource_cache.end(), [](const std::shared_ptr<Resource> & resource) {
    //    return resource.use_count() == 1;
    //});
    //resource_cache.erase(it, resource_cache.end()); this commented?

**Comment by JorxSS** [comment]
Yes if we substitute the commented code for resource_cache.clear(); It's not good because with that we don't use the benefits of the cache but the problem we have with the textures is gone. 
Then we thought the problem is how is managed the resource_cache.  

Maybe you find the problem is somewhere else, you are our expert Anabel
