### ISSUE TITLE
[BUG] Collider bug

### ISSUE THREAD

**Issue by RickyVimon** [Unnamed-Company/LittleOrionEngine#69]
**Player gets stuck in some spots**

**To Reproduce**
1. Go to a rock on the front part of the level.
2. Try to move towards the camera.
3. Now try to move to any of the sides.
4. The player colides with an invisible collider

![collider_bug3](https://user-images.githubusercontent.com/33130090/79251164-17e4b680-7e80-11ea-9944-76bcf5e634e9.gif)
![collider_bug1](https://user-images.githubusercontent.com/33130090/79250922-c1777800-7e7f-11ea-8831-207a66efdd5f.gif)
![collider_bug2](https://user-images.githubusercontent.com/33130090/79251053-f1268000-7e7f-11ea-9824-4b28f9ecc97d.gif)

**Comment by raulgonzalezupc** [comment]
Also in this part ^^
![image](https://user-images.githubusercontent.com/56253770/79257899-9b0b0a00-7e8a-11ea-89dc-1b4e88984ff5.png)

**Comment by JorxSS** [comment]
Fixed [here](https://github.com/OnionGalaxy/LittleOrionEngine/commit/23375d5d0205a6f2548aa640c0e71e0c09b28ac8)
