### ISSUE TITLE
[BUG] God mode camera is not being activated

### ISSUE THREAD

**Issue by yalania** [Unnamed-Company/LittleOrionEngine#70]
**Describe the bug**
In VS1 button 1 sometimes triger godmode and sometime it doesn't.

**To Reproduce**
1. Load the vs1 game scene
2. Press button 1 
3. Check if it have change to god mode
4. Try many times and see that sometimes it works and sometimes doesn't

**Expected behavior**
Pressig 1 always do what I expect.

**Comment by JorxSS** [comment]
Fixed [here](https://github.com/OnionGalaxy/LittleOrionEngine/commit/d00c71059299d0be342ca5c978693fddb22a1f8a)
