### ISSUE TITLE
[BUG] OctTree causes a lot of crashes in the Engine.

### ISSUE THREAD

**Issue by Pacasasgar** [Unnamed-Company/LittleOrionEngine#72]
OctTree has been commented in ModuleRender to avoid runtime crashes. It needs to be inspected and improved in order to be working again.

**Comment by Dartemiss** [comment]
Hey!
Octree was not working properly and made a lot of crashes on the engine. For this reason, we commented on the code that added objects to octree to prevent crashes.
If you go to module render, getcullingmeshes, you will see the commented code.

**Comment by Pacasasgar** [comment]
Hey Enrique, ok thanks! I will rename then this issue.

**Comment by mariofv** [comment]
This will be solved in #15
