### ISSUE TITLE
[BUG] Model prefabs cannot be saved with modifications

### ISSUE THREAD

**Issue by mariofv** [Unnamed-Company/LittleOrionEngine#73]
**Describe the bug**
When saving a scene with a gameobject that is a modified instance of a prefab that's being imported from a model, the modifications of this instance are not kept when loading.

**To Reproduce**
1. Load `fbx` level mesh.
2. Delete Zone X ext.
3. Save scene,
4. Load scene.

**Expected behavior**
Modifications on instances of model prefabs should be kept when saving scenes.

**Comment by yalania** [comment]
Fix in branch fix/prefabs_fixes I'm going to work there for all the issues.
