### ISSUE TITLE
[BUG] Model prefabs instances transformations are modified when saving/loading

### ISSUE THREAD

**Issue by mariofv** [Unnamed-Company/LittleOrionEngine#74]
**Describe the bug**
Some instances of some model prefabs, like `cube.fbx`, get their geoemtrical transformations modified when saving and then loading scene.

**To Reproduce**
Speak with @JorxSS.

**Comment by Dartemiss** [comment]
@yalania To add some info on this issue, also if you try to change the name of a prefab instantiated and you save the scene, when you load the scene the name won't change correctly. And if you try to Apply changes the console will throw an error.

**Comment by yalania** [comment]
if you modify the transform by using gizmos is not applied, because the boolean modified_by_user needs to be set to true for this changes, and I don't know where does it change.

For the name, as is part of the gameobject and not part of a component that is just not supported right now

**Comment by Dartemiss** [comment]
It happens modifying it with gizmos and with the inspector equally :(

**Comment by yalania** [comment]
steps to reproduce? I can't no reproduce it :(

**Comment by yalania** [comment]
For the names we will want this to be able to change the names of prefabs gameobjects? If we want it I will need to add another flag

**Comment by Dartemiss** [comment]
Mmm I think it can be useful yes! :D

**Comment by yalania** [comment]
Ok it is done in branch fix/prefabs_fixes
