### ISSUE TITLE
[BUG] Prefabs instances references are lost randomly after some pushes

### ISSUE THREAD

**Issue by mariofv** [Unnamed-Company/LittleOrionEngine#75]
**Describe the bug**
Sometimes, after a push that is not modifying the `.meta` files, references to prefabs are lost.

**To Reproduce**
This occurs randomly, we couldn't reproduce it consistently. One case when normally happens is after cloning the repo.

**Expected behavior**
Not losing instances references..

**Comment by yalania** [comment]
references in scenes?

**Comment by yalania** [comment]
The reason for this actually is that some assests are not imported, try to reimport all with the reimport All menu option. Also notice that assimps is giving error when loading some models.
