### ISSUE TITLE
[BUG] Children prefabs changes not saving

### ISSUE THREAD

**Issue by marcorod94** [Unnamed-Company/LittleOrionEngine#79]
**Describe the bug**
When you modified the components of the child of a prefab they arent save on a scene.

**To Reproduce**
When to play/pause the game the modified components of a children prefab aren't getting save so it will load the original information of the prefab.

**Expected behavior**
It is expected to get the exact information of the working scene not the original prefab information

**Comment by yalania** [comment]
I will close it for this one #99 to don't have it repeated
