### ISSUE TITLE
[FEATURE] Current state in Animation component

### ISSUE THREAD

**Issue by JoanStinson** [Unnamed-Company/LittleOrionEngine#83]
**Is your feature request related to a problem? Please describe.**
The problem is to easily understand the behaviors and the interaction between different states, so to have the current state being shown in the inspector to debug.

**Describe the solution you'd like**
In the Animation component have displayed the name of the current played state of the selected state machine.

**Comment by yalania** [comment]
This was added by Jordi in the animation branch, so I will close it.
