### ISSUE TITLE
[BUG] Prefabs disappearing after play/pause

### ISSUE THREAD

**Issue by marcorod94** [Unnamed-Company/LittleOrionEngine#88]
**Describe the bug**
After pressing the play/stop buttons the prefabs added to the scene disappear.

**To Reproduce**
Put a prefab in the scene then press play then press pause and the object disappears.

**Expected behavior**
The object should be kept in the scene with all the changes made to it

**Comment by yalania** [comment]
I checked it but it happens with prefabs and usual gameobejcts too. I think it is a problem with the scene manager.

**Comment by yalania** [comment]
So the tmp scene is not being save https://github.com/OnionGalaxy/LittleOrionEngine/blob/develop/Engine/Module/ModuleScene.cpp#L259

**Comment by Dartemiss** [comment]
Yes, i didnt have into account that case my bad, I fixed the issue on the brach #90
