### ISSUE TITLE
[BUG] Prefabs if they are not child of a gameobject don't preserve transform/components when saving/loading scene

### ISSUE THREAD

**Issue by Dartemiss** [Unnamed-Company/LittleOrionEngine#99]
**Describe the bug**
Prefabs don't work propertly when they are not child of a gameobject

**To Reproduce**
1. Create prefab and move it out of origin.
2. Create some components scripts
3. Save scene
4. Load scene
5. Prefabs won't preserve changes on saved scene

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by yalania** [comment]
As I was unable to reproduce it, I'm going to close it and if it happens again you can reopen it.
